# Generated by Django 3.0.5 on 2020-08-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=60)),
                ('txt', models.CharField(max_length=60)),
                ('indx', models.CharField(max_length=60)),
                ('remdate', models.CharField(max_length=60)),
                ('remtime', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
