# Generated by Django 3.0.5 on 2020-08-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindmeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='date',
        ),
    ]
