# Generated by Django 3.0.5 on 2020-08-05 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remindmeapp', '0002_remove_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
